[theme]
# Primary accent color for interactive elements.
primaryColor = "#18990B"

# Background color for the main content area.
backgroundColor = "#FCDDBC"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FFFBF6"

# Color used for almost all text.
textColor = "#160255"