[theme]
# Primary accent color for interactive elements.
primaryColor = "#DDFFD9"

# Background color for the main content area.
backgroundColor = "#FCDDBC"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FFFDFD"

# Color used for almost all text.
textColor = "#2D3047"